version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kbo_community
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: kbo-backend
    restart: unless-stopped
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/kbo_community

  frontend:
    build: ./frontend
    container_name: kbo-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data: